refactored 'due' code for uniformity.

diff --git a/due b/due
--- a/due
+++ b/due
@@ -39,10 +39,8 @@ find_element() {
 		# check if child exists
 		local index=$(( ${array[$level]} + 1 ))
 		local childcount=$(wc -l "$element" | awk '{print $1}')
-		if [ "$index" -le "1" ]; then
-            echo "invalid index" && exit 1 # invalid index
-		elif [ "$index" -gt "$childcount" ]; then
-            echo "invalid index" && exit 1 # invalid index
+		if [ "$index" -le "1" ] || [ "$index" -gt "$childcount" ]; then
+            echo "invalid index" && exit 1 # TODO - better error msg
 		else
 			element="$duedir/$(head -n $index "$element" | tail -n 1)"
 		fi
@@ -51,8 +49,12 @@ find_element() {
 	done
 }
 
-id() {
-    tr -dc 'A-F0-9' < /dev/urandom | dd status=none bs=1 count=32
+parent_id() {
+    if [[ "$1" == *"."* ]]; then
+        parentid=${1%.*}
+    else
+        parentid=""
+    fi
 }
 
 print_element() {
@@ -86,26 +88,27 @@ case "$1" in
         (( $# != 3 )) && echo "'add' requires two arguments" && exit 1
 
 		# find parent element
-        parentid=""
-        if [[ "$2" == *"."* ]]; then
-            parentid=${2%.*}
-        fi
-
+        parent_id "$2"
         find_element "$parentid" 
 
+        # compute a new random id
+		id=$(tr -dc 'A-F0-9' < /dev/urandom \
+            | dd status=none bs=1 count=32)
+
 		# add element to parent
-		id=$(id)
 		index=$(( "${2##*.}" + 1 ))
-		childcount=$(wc -l "$element" | awk '{print $1}')
+        childcount=$(wc -l "$element" | awk '{print $1-1}')
 		if [ "$index" -le "1" ]; then
-			echo "invalid index" && exit 1
+			echo "invalid index" && exit 1 # TODO better error msg
 		elif [ "$index" -gt "$childcount" ]; then
 			echo "$id" >> "$element"
 		else
 			sed -i "$index i $id" "$element"
 		fi
 
+        # create element
 		echo "$3" > "$duedir/$id"
+
 		echo "[+] added element '$2' '$3'"
 		;;
     help)
@@ -115,10 +118,11 @@ case "$1" in
 		# check argument length
         (( $# != 2 )) && echo "'hide' requires one argument" && exit 1
 
-        # find element to remove (to ensure it exists)
-        find_element $2
+        # find element
+        find_element "$2"
 		id="${element##*\/}"
 
+        # add element to hidefile
         echo "$id" >> "$hidefile"
         ;;
     list)
@@ -133,13 +137,8 @@ case "$1" in
 				| xargs head -n 1 -q | awk '{print NR " - " $1}'
         else
             # recursively print element argument
-            find_element $2
-
-            # find parent id
-            parentid=""
-            if [[ "$2" == *"."* ]]; then
-                parentid="${2%.*}."
-            fi
+            parent_id "$2"
+            find_element "$2"
 
 		    index=$(( "${2##*.}" + 1 ))
             print_element "$parentid" "$index" "$element" "0"
@@ -151,43 +150,35 @@ case "$1" in
             echo "'remove' requires three arguments" && exit 1
 
         # find element to remove (to ensure it exists)
-        find_element $2
+        find_element "$2"
 
-		# find src parent element
-        srcparentid=""
-        if [[ "$2" == *"."* ]]; then
-            srcparentid=${2%.*}
-        fi
-
-        find_element "$srcparentid" 
+		# find src parent element and index
+        parent_id "$2"
+        find_element "$parentid" 
 
 		srcindex=$(( "${2##*.}" + 1 ))
-        srcelement="$element"
-        id=$(head -n $srcindex "$srcelement" | tail -n 1)
+        srcparent="$element"
+        id=$(head -n $srcindex "$srcparent" | tail -n 1)
 
-		# find dst parent element
-        dstparentid=""
-        if [[ "$3" == *"."* ]]; then
-            dstparentid=${3%.*}
-        fi
+		# find dst parent element and index
+        parent_id "$3"
+        find_element "$parentid" 
 
-        find_element "$dstparentid" 
-
-        # add to dstelement
 		dstindex=$(( "${3##*.}" + 1 ))
+        dstparent="$element"
 		if [ "$dstindex" -le "1" ]; then
-			echo "invalid index" && exit 1
+			echo "invalid index" && exit 1 # TODO - better error msg
         fi
 
         # remove element from src parent
-		sed -i "$srcindex d" "$srcelement"
+		sed -i "$srcindex d" "$srcparent"
 
-        # add to dst parent
-		childcount=$(wc -l "$element" | awk '{print $1}')
+        # add element to dst parent
+		childcount=$(wc -l "$dstparent" | awk '{print $1-1}')
 		if [ "$dstindex" -gt "$childcount" ]; then
-			echo "$id" >> "$element"
+			echo "$id" >> "$dstparent"
 		else
-			sed -i "$dstindex i $id" "$element"
+			sed -i "$dstindex i $id" "$dstparent"
 		fi
 
 		echo "[|] moved element '$2' to '$3'"
@@ -197,7 +188,7 @@ case "$1" in
         (( $# != 2 )) && echo "'remove' requires one argument" && exit 1
 
         # find element to remove
-        find_element $2
+        find_element "$2"
 
         # ensure element has no children
 		childcount=$(wc -l "$element" | awk '{print $1}')
@@ -209,11 +200,7 @@ case "$1" in
         rm "$element"
 
 		# find parent element
-        parentid=""
-        if [[ "$2" == *"."* ]]; then
-            parentid=${2%.*}
-        fi
-
+        parent_id "$2"
         find_element "$parentid" 
 
         # remove element from parent
@@ -227,9 +214,10 @@ case "$1" in
         (( $# != 2 )) && echo "'unhide' requires one argument" && exit 1
 
         # find element to remove (to ensure it exists)
-        find_element $2
+        find_element "$2"
 		id="${element##*\/}"
 
+        # remove id from hidefile
         sed -i "/$id/d" "$hidefile"
         ;;
     version)
