general script refactoring. renamed variables, added comments, etc.

diff --git a/stash b/stash
--- a/stash
+++ b/stash
@@ -1,8 +1,7 @@
 #!/bin/bash
 
 version="1.0.3"
-usage() {
-    echo "USAGE $(basename $0) [COMMAND]
+usage="USAGE: $(basename $0) [COMMAND]
 COMMANDS:
     clip                copy a key's value to the clipboard
     get <key>           retrieve a value for the specified key
@@ -13,7 +12,6 @@ COMMANDS:
     set <key> <value>   store the value for the specified key
     unset <key>         remove values for the key (and all subkeys)
     version             display the applications version"
-}
 
 stashcode() {
     # print md5sum hash of value
@@ -75,7 +73,7 @@ case "$1" in
         done
         ;;
     help)
-        usage
+        echo "$usage"
         ;;
     init)
         # check argument length
@@ -151,7 +149,8 @@ case "$1" in
             mv $listfile $listfile.bak
             gpg -d -q $listfile.bak | sed "/^$key/d" \
                 | gpg -e -r $gpgusername > $listfile
-            [ $? -ne 0 ] && echo "failed to remove 'key' from stashfile" && exit 1
+            [ $? -ne 0 ] && \
+                echo "failed to remove 'key' from stashfile" && exit 1
 
             # remove key from stashfile
             stashfile="$stashdir/$(stashfile $key)"
@@ -171,7 +170,7 @@ case "$1" in
         echo "v$version"
         ;;
     *)
-        usage
+        echo "$usage"
         exit 1
         ;;
 esac
