updated for hyprland DE
Signed-off-by: Daniel Rammer <hamersaw@protonmail.com>

diff --git a/veil b/veil
--- a/veil
+++ b/veil
@@ -21,7 +21,7 @@ COMMAND:
 
 # check if applications are available
 [ ! $(which gpg) ] && echo "'gpg' not found in users PATH" && exit 1
-[ ! $(which xclip) ] && echo "'xclip' not found in users PATH" && exit 1
+[ ! $(which wl-copy) ] && echo "'wl-copy' not found in users PATH" && exit 1
 
 # initialize instance variables - set veildir if not already set
 [ -z "$veildir" ] && veildir="$HOME/.local/share/veil"
@@ -45,12 +45,10 @@ case "$1" in
         fi
 
         # copy to clip
-        echo "$value" | cut -f4- -d ' ' | tr -d '\n' | xclip -selection clipboard
-        $(sleep 3; echo -n "" | xclip -selection clipboard) &
-
-        # this should work, but doesn't when pasting as a firefox url
-        # https://stackoverflow.com/questions/22686866/why-has-xclip-loop-1-stopped-working
-        #echo "$value" | cut -f2- -d ' ' | tr -d '\n' | xclip -loops 1 -selection clipboard
+        # TODO @hamersaw `wl-copy -o` does not work on chrome in wayland yet
+        # so we do a hacky "wait 3 seconds then copy nothing to clipboard"
+        nohup bash -c "sleep 3; wl-copy -c" &>> /dev/null &
+        echo "$value" | cut -f4- -d ' ' | tr -d '\n' | wl-copy
         ;;
     create)
         # check argument length
diff --git a/veilmenu b/veilmenu
--- a/veilmenu
+++ b/veilmenu
@@ -1,40 +1,20 @@
 #!/usr/bin/env bash
 
-shopt -s nullglob globstar
+# necessary to print gpg cli password auth in new window
+GPG_TTY=$(tty)
+export GPG_TTY
 
-typeit=0
-if [[ $1 == "--type" ]]; then
-	typeit=1
-	shift
+password_keys=$(veil list-keys)
+if [ "${#password_keys}" -eq "0" ]; then
+  echo "failed to retrieve passwords"
+  sleep 1s
+  exit 1
 fi
 
-if [[ -n $WAYLAND_DISPLAY ]]; then
-	dmenu=dmenu-wl
-	xdotool="ydotool type --file -"
-elif [[ -n $DISPLAY ]]; then
-	dmenu=dmenu
-	xdotool="xdotool type --clearmodifiers --file -"
-else
-	echo "Error: No Wayland or X11 display detected" >&2
-	exit 1
-fi
+password_files=( "$password_keys" )
+password=$(printf '%s\n' "${password_files[@]}" | fzf)
 
-password_files=( "$(veil list-keys)" )
-
-password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")
-
-[[ -n $password ]] || exit
-
-if [[ $typeit -eq 0 ]]; then
-    IFS=":" read -r group key <<< "$password"
-    #echo "$group $key" | xclip -selection clipboard
-    veil clip "$group" "$key"
-
-	#pass show -c "$password" 2>/dev/null
-else
-    IFS=":" read -r group key <<< "$password"
-    #echo "$group $key" | xclip -selection clipboard
-    veil clip "$group" "$key"
-
-	#pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
+if [ -n "$password" ]; then
+  IFS=":" read -r group key <<< "$password"
+  veil clip "$group" "$key"
 fi
